### ISSUE TITLE
Fix 'Size is invalid' error when regions of form 'pct:<float>' are requested

### ISSUE THREAD

**Issue by jchristo4** [sul-dlss/djatoka#11]

**Comment by mejackreed** [comment]
An example https://stacks.stanford.edu/image/iiif/hg676jb4964%2F0380_796-44/0,0,4096,3820/pct:6.25/0/default.jpg

**Comment by mejackreed** [comment]
Maybe this line https://github.com/sul-dlss/djatoka/blob/master/lib/djatoka/iiif_request.rb#L132

Should be something more like this:

```ruby
when /^pct:(\d*\.?\d?)+$/i
```

Tried to clone and run tests to change but I wasn't able to run the tests

**Comment by jchristo4** [comment]
@mejackreed Fixed. https://stacks.stanford.edu/image/iiif/hg676jb4964%2F0380_796-44/0,0,4096,3820/pct:6.25/0/default.jpg works now.

**Comment by mejackreed** [comment]
Thanks @jchristo4 ! Working great now http://mejackreed.github.io/Leaflet-IIIF/examples/example.html
